import { CORES, LETRAS } from "../../constants/tema";

const styles = {
  container: {
    flex: 1,
    paddingHorizontal: 5,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#FFF",
    gap: 5,
    paddingTop: 80,
  },
  line: {
    width: "95%",
    height: 1,
    backgroundColor: "#8FBC8F",
  },
  titulo: {
    color: CORES.verdeEscuro,
    fontSize: LETRAS.xl,
    fontWeight: "600",
  },
  card: {
    width: 380,
    gap: 8,
    padding: 10,
    borderWidth: 2,
    borderColor: CORES.verdeClaro,
    marginVertical: 10,
    alignItems: "center",
    borderRadius: 10,
  },
  name: {
    width: "95%",
    textAlign: "left",
    color: "#C40C0C",
    fontWeight: "800",
    fontSize: LETRAS.md,
  },
  contato: {
    padding: 3,
    width: "80%",
    textAlign: "center",
    color: "blue",
    fontWeight: "600",
    fontSize: LETRAS.sm,
  },
  t: {
    width: "90%",
    textAlign: "center",
    color: CORES.verdeClaro,
    fontWeight: "900",
    fontSize: LETRAS.md,
  },
  textC: {
    width: "90%",
    textAlign: "left",
    color: CORES.verdeEscuro,
    fontWeight: "600",
    fontSize: LETRAS.sm,
  },
  box: {
    flexDirection: "row",
    width: "55%",
    positon: "absolute",
    top: 0,
    left: "-64",
  },
  pendente: {
    width: "80%",
    textAlign: "center",
    color: "#C40C0C",
    fontWeight: "700",
    fontSize: LETRAS.lg,
    borderWidth: 2,
    borderColor: CORES.verdeMedio,
    borderRadius: 5,
  },
  text2: {
    width: "90%",
    color: CORES.verdeClaro,
    fontWeight: "700",
    fontSize: LETRAS.md,
  },
  moreInformation: {
    width: "90%",
    borderRadius: 5,
    padding: 5,
    backgroundColor: CORES.verdeEscuro,
    marginLeft: 10,
  },
  more: {
    fontSize: LETRAS.md,
    fontWeight: "700",
    textAlign: "center",
    color: CORES.branco,
  },
  modalContainer: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    backgroundColor: "rgba(0, 0, 0, 0.5)",
  },
  modalContent: {
    width: "80%",
    backgroundColor: "#FFF",
    borderRadius: 10,
    padding: 20,
    maxHeight: "80%",
  },
  modalTitle: {
    fontSize: 18,
    fontWeight: "bold",
    color: "#256c42",
    textAlign: "center",
    marginBottom: 10,
  },
  modalText: {
    fontSize: 15,
    marginBottom: 10,
    fontWeight: "700",
    color: "#006400",
  },
  modalLabel: {
    fontSize: 15,
    fontWeight: "900",
    color: "#8FBC8F",
  },
  closeButton: {
    marginTop: 10,
    padding: 8,
    borderWidth: 2,
    borderColor: "#256c42",
    borderRadius: 5,
    alignItems: "center",
  },
  closeButtonText: {
    color: "#256c42",
    fontSize: 18,
    fontWeight: "bold",
  },
  statusButton: {
    marginTop: 5,
    padding: 10,
    backgroundColor: "#256c42",
    borderRadius: 5,
    alignItems: "center",
  },
};

export default styles;
